// packages/react/src/composite/CompositeCanvas.tsx
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, type ReactNode } from 'react';
import {
  SLD_LAYOUT,
  firstFormat,
  linkConnections,
  lineConnections,
  type CompositeLayout,
  type ChildLayout,
  type CompositeLineLayout,
  type ExternalConnectionTip,
  type Point
} from '@sld-kit/core';
import { createPanZoom, type ContentBounds } from '../panzoom';
import { useStore } from '../useStore';
import { DEFAULT_POSITION_TOKENS, DEFAULT_CHILD_NOT_FOUND, type PositionTokens } from '../labels';
import type { FormatResolver } from '../format';
import { DEFAULT_VIEW_STYLE, type SldViewStyle } from '../style';
import { ChildDiagramView } from './ChildDiagramView';
import { SelectionFrame } from './SelectionFrame';

export interface CompositeCanvasProps {
  layout: CompositeLayout;
  selectedId?: string | null;
  /** Currently selected manual line (shows its draggable bend handles). */
  selectedLineId?: string | null;
  interactive?: boolean;
  /**
   * Explore mode: children's transforms are read-only, but a click flies into a
   * child (`onChildFocus`) and the `focusedId` child's operable internals fire
   * `onElementActivate`. Editing chrome (selection/rotation/draw) is inert here.
   */
  explore?: boolean;
  /** In explore mode, the child currently flown into (its internals are live). */
  focusedId?: string | null;
  /**
   * Draw mode: clicking the canvas fires `onCanvasPoint` (snapped to the nearest
   * connection dot when close) instead of clearing the selection. The consumer
   * accumulates the points and commits a line; a double-click fires `onDrawCommit`.
   */
  drawMode?: boolean;
  /** Connection dots a drawn end can snap to (from `engine.externalConnectionTips`). */
  snapTargets?: ExternalConnectionTip[];
  /** In-progress polyline being drawn, in composite coordinates. */
  draftPoints?: Point[];
  /** CSS class per position type; the consumer's stylesheet supplies the colors. */
  tokens?: PositionTokens;
  /** Per-child color class override (e.g. a voltage bucket). */
  childColorClass?: (child: ChildLayout) => string | null;
  /**
   * Per-child override for *connection* colour only, so lines can be coloured on
   * a different axis than the boxes/bars. `undefined` keeps connections on
   * `childColorClass`.
   */
  childConnectionColorClass?: (child: ChildLayout) => string | null;
  /** Per-line color class override (e.g. a voltage bucket, when both ends match). */
  lineColorClass?: (line: CompositeLineLayout) => string | null;
  /** Per-element overlay returning an `ElementFormat`, forwarded to every child. */
  formatResolver?: FormatResolver | null;
  /** Numeric presentation config for the children and the composite chrome. */
  style?: SldViewStyle;
  showPositionLabels?: boolean;
  showBusBarLabels?: boolean;
  showConnectionLabels?: boolean;
  /** The always-on child diagram name (issue #17); on by default. */
  showChildNames?: boolean;
  /** Fallback text when a child diagram can't be resolved. */
  notFoundLabel?: string;
  /** Rendered last inside the `<svg>` — where the explorer injects flow overlays. */
  children?: ReactNode;

  onChildDown?: (detail: { id: string; event: React.PointerEvent }) => void;
  onChildFocus?: (detail: { id: string; event: React.PointerEvent }) => void;
  onElementActivate?: (detail: { instanceId: string; elementId: string }) => void;
  onRotateStart?: (detail: { event: React.PointerEvent }) => void;
  onClearSelection?: () => void;
  onLinkDown?: (detail: { connectionId: string; event: React.PointerEvent }) => void;
  onLineDown?: (detail: { id: string; event: React.PointerEvent }) => void;
  onLineVertexDown?: (detail: { id: string; index: number; event: React.PointerEvent }) => void;
  /** Remove an intermediate bend (double-click a vertex handle). */
  onLineVertexDelete?: (detail: { id: string; index: number }) => void;
  /** Add a bend: `index` is the segment (between vertex `index` and `index+1`). */
  onLineSegmentDown?: (detail: { id: string; index: number; point: Point; event: React.PointerEvent }) => void;
  onCanvasPoint?: (detail: { point: Point; snap: { instanceId: string; connectionId: string } | null }) => void;
  onDrawCommit?: () => void;
}

/** Imperative API, obtained with a `ref` — the analogue of Svelte's `bind:this`. */
export interface CompositeCanvasHandle {
  clientToSvg(clientX: number, clientY: number): Point;
  zoomToFit(): void;
  zoomIn(): void;
  zoomOut(): void;
  /** Smoothly frame an arbitrary world rect (e.g. a child's `worldBounds`). */
  flyTo(bounds: ContentBounds, opts?: { durationMs?: number }): void;
  /** Smoothly return to the whole-composite fit. */
  flyToFit(opts?: { durationMs?: number }): void;
}

/** Snap distance for drawn ends, in composite (SVG) units. */
const SNAP_RADIUS = 16;

/**
 * SVG host of the composite. A sibling of `SldCanvas`, sharing only the pan/zoom
 * mechanics (via `createPanZoom`). Renders the inter-diagram links beneath the
 * children, each child as a rigid transformed group, and the rotation/selection
 * chrome for the active child on top. The flow overlays go in `children`.
 */
export const CompositeCanvas = forwardRef<CompositeCanvasHandle, CompositeCanvasProps>(function CompositeCanvas(
  {
    layout,
    selectedId = null,
    selectedLineId = null,
    interactive = true,
    explore = false,
    focusedId = null,
    drawMode = false,
    snapTargets = [],
    draftPoints = [],
    tokens = DEFAULT_POSITION_TOKENS,
    childColorClass = () => null,
    childConnectionColorClass,
    lineColorClass = () => null,
    formatResolver = null,
    style = DEFAULT_VIEW_STYLE,
    showPositionLabels = true,
    showBusBarLabels = true,
    showConnectionLabels = true,
    showChildNames = true,
    notFoundLabel = DEFAULT_CHILD_NOT_FOUND,
    children,
    onChildDown,
    onChildFocus,
    onElementActivate,
    onRotateStart,
    onClearSelection,
    onLinkDown,
    onLineDown,
    onLineVertexDown,
    onLineVertexDelete,
    onLineSegmentDown,
    onCanvasPoint,
    onDrawCommit
  },
  ref
) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const suppressNextClick = useRef(false);

  const cs = style.composite;

  // `layout` is read lazily through a ref so the pan/zoom instance stays stable
  // for the life of the canvas (recreating it would reset the viewBox).
  const layoutRef = useRef(layout);
  layoutRef.current = layout;

  const pz = useMemo(
    () =>
      createPanZoom(
        () => svgRef.current,
        () => layoutRef.current.bounds
      ),
    []
  );
  const viewBox = useStore(pz.viewBox);
  const spaceDown = useStore(pz.spaceDown);
  const panning = useStore(pz.panning);

  const selectedChild = selectedId ? (layout.children.find((c) => c.instance.id === selectedId) ?? null) : null;
  const selectedLine = selectedLineId ? (layout.lines.find((l) => l.line.id === selectedLineId) ?? null) : null;

  useImperativeHandle(
    ref,
    (): CompositeCanvasHandle => ({
      clientToSvg: (x, y) => pz.clientToSvg(x, y),
      zoomToFit: () => pz.zoomToFit(),
      zoomIn: () => pz.zoomIn(),
      zoomOut: () => pz.zoomOut(),
      flyTo: (bounds, opts) => pz.flyTo(bounds, opts),
      flyToFit: (opts) => pz.flyToFit(opts)
    }),
    [pz]
  );

  useEffect(() => {
    pz.zoomToFit();
  }, [pz]);

  // Non-passive wheel: React's synthetic onWheel can't reliably preventDefault.
  useEffect(() => {
    const el = svgRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      pz.handleWheel(e);
    };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, [pz]);

  useEffect(() => {
    const down = (e: KeyboardEvent) => pz.handleKey(e, true);
    const up = (e: KeyboardEvent) => pz.handleKey(e, false);
    window.addEventListener('keydown', down);
    window.addEventListener('keyup', up);
    return () => {
      window.removeEventListener('keydown', down);
      window.removeEventListener('keyup', up);
    };
  }, [pz]);

  function nearestSnap(p: Point): ExternalConnectionTip | null {
    let best: ExternalConnectionTip | null = null;
    let bestDist = SNAP_RADIUS;
    for (const t of snapTargets) {
      const d = Math.hypot(t.point.x - p.x, t.point.y - p.y);
      if (d <= bestDist) {
        bestDist = d;
        best = t;
      }
    }
    return best;
  }

  const handleLinkDown = (connectionId: string, e: React.PointerEvent) => {
    if (!interactive) return;
    e.stopPropagation();
    onLinkDown?.({ connectionId, event: e });
  };
  const handleLineDown = (id: string, e: React.PointerEvent) => {
    if (!interactive) return;
    e.stopPropagation();
    onLineDown?.({ id, event: e });
  };
  const handleVertexDown = (id: string, index: number, e: React.PointerEvent) => {
    if (!interactive) return;
    e.stopPropagation();
    e.preventDefault();
    // A handle gesture re-renders the chrome; swallow the trailing background
    // click so it can't clear the current line selection.
    suppressNextClick.current = true;
    onLineVertexDown?.({ id, index, event: e });
  };
  const handleVertexDblClick = (id: string, index: number, e: React.MouseEvent) => {
    if (!interactive) return;
    e.stopPropagation();
    onLineVertexDelete?.({ id, index });
  };
  const handleSegmentDown = (id: string, index: number, point: Point, e: React.PointerEvent) => {
    if (!interactive) return;
    e.stopPropagation();
    e.preventDefault();
    suppressNextClick.current = true;
    onLineSegmentDown?.({ id, index, point, event: e });
  };

  const handlePointerDown = useCallback(
    (e: React.PointerEvent<SVGSVGElement>) => {
      // In draw mode a tap/click places a point, so only pinch/space/middle pan.
      pz.tryStartPan(e.nativeEvent, { panOnDrag: !drawMode, background: e.target === svgRef.current });
    },
    [pz, drawMode]
  );
  const handlePointerMove = useCallback((e: React.PointerEvent<SVGSVGElement>) => pz.movePan(e.nativeEvent), [pz]);
  const handlePointerUp = useCallback(
    (e: React.PointerEvent<SVGSVGElement>) => {
      const res = pz.endPan(e.nativeEvent);
      if (res.wasPanning) suppressNextClick.current = res.moved;
    },
    [pz]
  );

  const handleClick = useCallback(
    (e: React.MouseEvent<SVGSVGElement>) => {
      if (suppressNextClick.current) {
        suppressNextClick.current = false;
        return;
      }
      if (drawMode && interactive) {
        const p = pz.clientToSvg(e.clientX, e.clientY);
        const snap = nearestSnap(p);
        onCanvasPoint?.({
          point: snap ? snap.point : p,
          snap: snap ? { instanceId: snap.instanceId, connectionId: snap.connectionId } : null
        });
        return;
      }
      if (e.target === svgRef.current) onClearSelection?.();
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [pz, drawMode, interactive, snapTargets, onCanvasPoint, onClearSelection]
  );

  const handleDblClick = useCallback(() => {
    if (drawMode && interactive) onDrawCommit?.();
  }, [drawMode, interactive, onDrawCommit]);

  const cursorClass = panning
    ? 'cursor-grabbing'
    : drawMode && interactive
      ? 'cursor-crosshair'
      : spaceDown || !drawMode
        ? 'cursor-grab'
        : '';

  const fmt = formatResolver ?? undefined;

  return (
    <svg
      ref={svgRef}
      className={`h-full w-full touch-none ${cursorClass}`}
      viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.w} ${viewBox.h}`}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
      onPointerCancel={handlePointerUp}
      onPointerEnter={() => pz.setPointerInside(true)}
      onPointerLeave={() => pz.setPointerInside(false)}
      onClick={handleClick}
      onDoubleClick={handleDblClick}
    >
      {/* Inter-diagram auto-links (dashed), underneath the children. A commissioning
          overlay on the shared child connection restyles the tie-line; tagging it
          in either diagram is enough (see `linkConnections`). */}
      {layout.links.map((link) => {
        const lf = firstFormat(linkConnections(link, layout.children), fmt);
        const pts = link.points.map((p) => `${p.x},${p.y}`).join(' ');
        return (
          <g key={link.connectionId}>
            <polyline
              points={pts}
              fill="none"
              className="stroke-primary/70"
              strokeWidth={lf?.strokeWidth ?? cs.linkStrokeWidth}
              strokeDasharray={lf?.dashArray ?? cs.linkDashArray}
            />
            {link.points.map((p, i) => (
              <circle key={i} cx={p.x} cy={p.y} r={SLD_LAYOUT.nodeDotRadius} className="fill-primary/70" />
            ))}
            {/* Wide transparent hit target: select an auto-link to convert it to a manual line. */}
            <polyline
              points={pts}
              fill="none"
              stroke="transparent"
              strokeWidth={style.hitStrokeWidth}
              className={interactive && !drawMode ? 'pointer-events-auto cursor-pointer' : undefined}
              onPointerDown={(e) => handleLinkDown(link.connectionId, e)}
            />
          </g>
        );
      })}

      {/* Manual lines (solid), underneath the children — matches the SVG export. */}
      {layout.lines.map((ln) => {
        const cls = lineColorClass(ln);
        const lf = firstFormat(lineConnections(ln.line, layout.children), fmt);
        return (
          <polyline
            key={ln.line.id}
            points={ln.points.map((p) => `${p.x},${p.y}`).join(' ')}
            fill="none"
            stroke={cls ? 'currentColor' : undefined}
            className={cls ?? 'stroke-primary'}
            style={cls ? { color: 'var(--sld-pos)' } : undefined}
            strokeWidth={
              ln.line.id === selectedLineId ? cs.lineSelectedStrokeWidth : (lf?.strokeWidth ?? cs.lineStrokeWidth)
            }
            strokeDasharray={lf?.dashArray ?? undefined}
          />
        );
      })}

      {/* Children in z-order. */}
      {layout.children.map((child) => (
        <ChildDiagramView
          key={child.instance.id}
          child={child}
          interactive={interactive}
          explore={explore}
          focused={explore && child.instance.id === focusedId}
          dimmed={explore && focusedId !== null && child.instance.id !== focusedId}
          tokens={tokens}
          colorClass={childColorClass(child)}
          connectionColorClass={childConnectionColorClass ? childConnectionColorClass(child) : undefined}
          formatResolver={formatResolver}
          style={style}
          showPositionLabels={showPositionLabels}
          showBusBarLabels={showBusBarLabels}
          showConnectionLabels={showConnectionLabels}
          showChildNames={showChildNames}
          notFoundLabel={notFoundLabel}
          onChildDown={onChildDown}
          onChildFocus={onChildFocus}
          onElementActivate={onElementActivate}
        />
      ))}

      {/* Selection + rotation chrome on top. */}
      {selectedChild && (
        <SelectionFrame child={selectedChild} interactive={interactive} onRotateStart={onRotateStart} />
      )}

      {/* Manual-line chrome on top: hit targets for selection. */}
      {!drawMode &&
        layout.lines.map((ln) => (
          <polyline
            key={`hit:${ln.line.id}`}
            points={ln.points.map((p) => `${p.x},${p.y}`).join(' ')}
            fill="none"
            stroke="transparent"
            strokeWidth={style.hitStrokeWidth}
            className={interactive ? 'pointer-events-auto cursor-pointer' : undefined}
            onPointerDown={(e) => handleLineDown(ln.line.id, e)}
          />
        ))}

      {/* Bend chrome needs vertex ↔ point 1:1 so a vertex index maps straight to its
          resolved world position; if some vertex didn't resolve we hide the handles
          rather than misplace them. */}
      {selectedLine && interactive && !drawMode && selectedLine.points.length === selectedLine.line.vertices.length && (
        <>
          {/* Hollow "add" handles at each segment midpoint: click-drag to insert
                a new bend; the segment index maps to a vertex insert position. */}
          {selectedLine.points.slice(0, -1).map((p, i) => {
            const mid = {
              x: (p.x + selectedLine.points[i + 1].x) / 2,
              y: (p.y + selectedLine.points[i + 1].y) / 2
            };
            return (
              <circle
                key={`add:${i}`}
                cx={mid.x}
                cy={mid.y}
                r={cs.addHandleRadius}
                className="fill-background stroke-primary/50 pointer-events-auto cursor-copy"
                strokeWidth={cs.handleStrokeWidth}
                strokeDasharray={cs.addHandleDashArray}
                onPointerDown={(e) => handleSegmentDown(selectedLine.line.id, i, mid, e)}
              >
                <title>Click to add a bend</title>
              </circle>
            );
          })}

          {/* Only free bend vertices are draggable; anchored ends follow their
                child. Drawn at the resolved point. Double-click removes. */}
          {selectedLine.line.vertices.map((v, i) =>
            v.kind === 'point' || v.kind === 'rel' ? (
              <circle
                key={`vtx:${i}`}
                cx={selectedLine.points[i].x}
                cy={selectedLine.points[i].y}
                r={cs.vertexHandleRadius}
                className="fill-background stroke-primary pointer-events-auto cursor-grab"
                strokeWidth={cs.handleStrokeWidth}
                onPointerDown={(e) => handleVertexDown(selectedLine.line.id, i, e)}
                onDoubleClick={(e) => handleVertexDblClick(selectedLine.line.id, i, e)}
              >
                <title>Drag to move · double-click to delete</title>
              </circle>
            ) : null
          )}
        </>
      )}

      {/* Draw-mode overlay: snap targets + in-progress polyline. */}
      {drawMode && interactive && (
        <>
          {snapTargets.map((t, i) => (
            <circle
              key={`snap:${i}`}
              cx={t.point.x}
              cy={t.point.y}
              r={cs.snapHandleRadius}
              className="fill-background stroke-primary/60"
              strokeWidth={cs.handleStrokeWidth}
            />
          ))}
          {draftPoints.length > 0 && (
            <>
              {draftPoints.length > 1 && (
                <polyline
                  points={draftPoints.map((p) => `${p.x},${p.y}`).join(' ')}
                  fill="none"
                  className="stroke-primary"
                  strokeWidth={cs.draftStrokeWidth}
                  strokeDasharray={cs.draftDashArray}
                />
              )}
              {draftPoints.map((p, i) => (
                <circle key={`draft:${i}`} cx={p.x} cy={p.y} r={cs.draftPointRadius} className="fill-primary" />
              ))}
            </>
          )}
        </>
      )}

      {children}
    </svg>
  );
});

// packages/svelte/src/lib/composite/CompositeCanvas.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import {
    SLD_LAYOUT,
    firstFormat,
    linkConnections,
    lineConnections,
    type CompositeLayout,
    type ChildLayout,
    type CompositeLineLayout,
    type ExternalConnectionTip,
    type Point
  } from '@sld-kit/core';
  import { createPanZoom, type ContentBounds } from '../panzoom';
  import { DEFAULT_POSITION_TOKENS, DEFAULT_CHILD_NOT_FOUND, type PositionTokens } from '../labels';
  import type { FormatResolver } from '../format';
  import { DEFAULT_VIEW_STYLE, type SldViewStyle } from '../style';
  import ChildDiagramView from './ChildDiagramView.svelte';
  import SelectionFrame from './SelectionFrame.svelte';

  /**
   * SVG host of the composite. A sibling of `SldCanvas`, sharing only the
   * pan/zoom mechanics (via `createPanZoom`). Renders the inter-diagram links
   * beneath the children, each child as a rigid transformed group, and the
   * rotation/selection chrome for the active child on top.
   */
  export let layout: CompositeLayout;
  export let selectedId: string | null = null;
  /** Currently selected manual line (shows its draggable bend handles). */
  export let selectedLineId: string | null = null;
  export let interactive: boolean = true;
  /**
   * Explore mode: children's transforms are read-only, but a click flies into a
   * child (`childfocus`) and the `focusedId` child's operable internals emit
   * `elementactivate`. Editing chrome (selection/rotation/draw) is inert here.
   */
  export let explore: boolean = false;
  /** In explore mode, the child currently flown into (its internals are live). */
  export let focusedId: string | null = null;
  /**
   * Draw mode: clicking the canvas emits `canvaspoint` (snapped to the nearest
   * connection dot when close) instead of clearing the selection. The consumer
   * accumulates the points and commits a line; a double-click emits `drawcommit`.
   */
  export let drawMode: boolean = false;
  /** Connection dots a drawn end can snap to (from `engine.externalConnectionTips`). */
  export let snapTargets: ExternalConnectionTip[] = [];
  /** In-progress polyline being drawn, in composite coordinates. */
  export let draftPoints: Point[] = [];
  /** CSS class per position type; the consumer's stylesheet supplies the colors. */
  export let tokens: PositionTokens = DEFAULT_POSITION_TOKENS;
  /**
   * Per-child color class override (e.g. a voltage bucket). Stays agnostic: the
   * consumer decides the class from the child's resolved document.
   */
  export let childColorClass: (child: ChildLayout) => string | null = () => null;
  /**
   * Per-line color class override (e.g. a voltage bucket, set only when both
   * ends share a voltage). Same contract as `childColorClass`: the class must
   * set `--sld-pos`; `null` falls back to the neutral primary stroke.
   */
  export let lineColorClass: (line: CompositeLineLayout) => string | null = () => null;
  /**
   * Commissioning overlay (new vs. existing assets): a single resolver returning
   * a per-element `ElementFormat`, forwarded to every child. It reads element
   * `data`, so one resolver spans all children. `null` (default) = unchanged.
   */
  export let formatResolver: FormatResolver | null = null;
  /**
   * Numeric presentation config for the children and the composite chrome
   * (link/line stroke widths, dash patterns, handle radii). Defaults reproduce
   * today's look; override via `resolveViewStyle({...})`.
   */
  export let style: SldViewStyle = DEFAULT_VIEW_STYLE;
  /** Label-visibility toggles, forwarded to every child. */
  export let showPositionLabels: boolean = true;
  export let showBusBarLabels: boolean = true;
  export let showConnectionLabels: boolean = true;
  /**
   * The always-on child diagram name (issue #17). Independent of the label
   * toggles above; on by default.
   */
  export let showChildNames: boolean = true;
  /** Fallback text when a child diagram can't be resolved. */
  export let notFoundLabel: string = DEFAULT_CHILD_NOT_FOUND;

  const dispatch = createEventDispatcher<{
    childdown: { id: string; event: PointerEvent };
    rotatestart: { event: PointerEvent };
    clearselection: void;
    linkdown: { connectionId: string; event: PointerEvent };
    linedown: { id: string; event: PointerEvent };
    linevertexdown: { id: string; index: number; event: PointerEvent };
    /** Remove an intermediate bend (double-click a vertex handle). */
    linevertexdelete: { id: string; index: number };
    /** Add a bend: `index` is the segment (between vertex `index` and `index+1`). */
    linesegmentdown: { id: string; index: number; point: Point; event: PointerEvent };
    canvaspoint: { point: Point; snap: { instanceId: string; connectionId: string } | null };
    drawcommit: void;
  }>();

  /** Snap distance for drawn ends, in composite (SVG) units. */
  const SNAP_RADIUS = 16;

  let svgEl: SVGSVGElement;
  let suppressNextClick = false;

  $: cs = style.composite;
  $: selectedLine = selectedLineId ? layout.lines.find((l) => l.line.id === selectedLineId) ?? null : null;

  function nearestSnap(p: Point): ExternalConnectionTip | null {
    let best: ExternalConnectionTip | null = null;
    let bestDist = SNAP_RADIUS;
    for (const t of snapTargets) {
      const d = Math.hypot(t.point.x - p.x, t.point.y - p.y);
      if (d <= bestDist) {
        bestDist = d;
        best = t;
      }
    }
    return best;
  }

  function handleLinkDown(connectionId: string, e: PointerEvent) {
    if (!interactive) return;
    e.stopPropagation();
    dispatch('linkdown', { connectionId, event: e });
  }

  function handleLineDown(id: string, e: PointerEvent) {
    if (!interactive) return;
    e.stopPropagation();
    dispatch('linedown', { id, event: e });
  }

  function handleVertexDown(id: string, index: number, e: PointerEvent) {
    if (!interactive) return;
    e.stopPropagation();
    e.preventDefault();
    // A handle gesture re-renders the chrome; swallow the trailing background
    // click so it can't clear the current line selection.
    suppressNextClick = true;
    dispatch('linevertexdown', { id, index, event: e });
  }

  function handleVertexDblClick(id: string, index: number, e: MouseEvent) {
    if (!interactive) return;
    e.stopPropagation();
    dispatch('linevertexdelete', { id, index });
  }

  function handleSegmentDown(id: string, index: number, point: Point, e: PointerEvent) {
    if (!interactive) return;
    e.stopPropagation();
    e.preventDefault();
    suppressNextClick = true;
    dispatch('linesegmentdown', { id, index, point, event: e });
  }

  const pz = createPanZoom(
    () => svgEl,
    () => layout.bounds
  );
  const viewBox = pz.viewBox;
  const spaceDown = pz.spaceDown;
  const panning = pz.panning;

  $: selectedChild = selectedId ? layout.children.find((c) => c.instance.id === selectedId) ?? null : null;

  export function clientToSvg(clientX: number, clientY: number): Point {
    return pz.clientToSvg(clientX, clientY);
  }

  export function zoomToFit() {
    pz.zoomToFit();
  }

  /** Smoothly frame an arbitrary world rect (e.g. a child's `worldBounds`). */
  export function flyTo(bounds: ContentBounds, opts?: { durationMs?: number }) {
    pz.flyTo(bounds, opts);
  }

  /** Smoothly return to the whole-composite fit. */
  export function flyToFit(opts?: { durationMs?: number }) {
    pz.flyToFit(opts);
  }

  function handlePointerDown(e: PointerEvent) {
    if (pz.tryStartPan(e)) return;
  }

  function handlePointerMove(e: PointerEvent) {
    pz.movePan(e);
  }

  function handlePointerUp(e: PointerEvent) {
    const res = pz.endPan(e);
    if (res.wasPanning) suppressNextClick = res.moved;
  }

  function handleClick(e: MouseEvent) {
    if (suppressNextClick) {
      suppressNextClick = false;
      return;
    }
    if (drawMode && interactive) {
      const p = pz.clientToSvg(e.clientX, e.clientY);
      const snap = nearestSnap(p);
      dispatch('canvaspoint', {
        point: snap ? snap.point : p,
        snap: snap ? { instanceId: snap.instanceId, connectionId: snap.connectionId } : null
      });
      return;
    }
    if (e.target === svgEl) dispatch('clearselection');
  }

  function handleDblClick() {
    if (drawMode && interactive) dispatch('drawcommit');
  }

  $: cursorClass = $panning
    ? 'cursor-grabbing'
    : $spaceDown
      ? 'cursor-grab'
      : drawMode && interactive
        ? 'cursor-crosshair'
        : '';

  onMount(() => {
    pz.zoomToFit();
  });
</script>

<svelte:window on:keydown={(e) => pz.handleKey(e, true)} on:keyup={(e) => pz.handleKey(e, false)} />

<!-- svelte-ignore a11y-no-static-element-interactions a11y-click-events-have-key-events -->
<svg
  bind:this={svgEl}
  class="h-full w-full touch-none {cursorClass}"
  viewBox="{$viewBox.x} {$viewBox.y} {$viewBox.w} {$viewBox.h}"
  on:wheel|preventDefault={pz.handleWheel}
  on:pointerdown={handlePointerDown}
  on:pointermove={handlePointerMove}
  on:pointerup={handlePointerUp}
  on:pointerenter={() => pz.setPointerInside(true)}
  on:pointerleave={() => pz.setPointerInside(false)}
  on:click={handleClick}
  on:dblclick={handleDblClick}
>
  <!-- Inter-diagram auto-links (dashed), underneath the children. A commissioning
       overlay on the shared child connection restyles the tie-line (dash / width);
       tagging it in either diagram is enough (see `linkConnections`). -->
  {#each layout.links as link (link.connectionId)}
    {@const lf = firstFormat(linkConnections(link, layout.children), formatResolver ?? undefined)}
    <polyline
      points={link.points.map((p) => `${p.x},${p.y}`).join(' ')}
      fill="none"
      class="stroke-primary/70"
      stroke-width={lf?.strokeWidth ?? cs.linkStrokeWidth}
      stroke-dasharray={lf?.dashArray ?? cs.linkDashArray}
    />
    {#each link.points as p}
      <circle cx={p.x} cy={p.y} r={SLD_LAYOUT.nodeDotRadius} class="fill-primary/70" />
    {/each}
    <!-- Wide transparent hit target: select an auto-link to convert it to a manual line. -->
    <polyline
      points={link.points.map((p) => `${p.x},${p.y}`).join(' ')}
      fill="none"
      stroke="transparent"
      stroke-width={style.hitStrokeWidth}
      class:pointer-events-auto={interactive && !drawMode}
      class:cursor-pointer={interactive && !drawMode}
      on:pointerdown={(e) => handleLinkDown(link.connectionId, e)}
    />
  {/each}

  <!-- Manual lines (solid), underneath the children — matches the SVG export.
       Colored by the consumer's `lineColorClass` (e.g. a voltage bucket) exactly
       like a child's connections; falls back to the neutral primary stroke. -->
  {#each layout.lines as ln (ln.line.id)}
    {@const cls = lineColorClass(ln)}
    {@const lf = firstFormat(lineConnections(ln.line, layout.children), formatResolver ?? undefined)}
    <polyline
      points={ln.points.map((p) => `${p.x},${p.y}`).join(' ')}
      fill="none"
      stroke={cls ? 'currentColor' : undefined}
      class={cls ?? 'stroke-primary'}
      style={cls ? 'color: hsl(var(--sld-pos))' : ''}
      stroke-width={ln.line.id === selectedLineId
        ? cs.lineSelectedStrokeWidth
        : (lf?.strokeWidth ?? cs.lineStrokeWidth)}
      stroke-dasharray={lf?.dashArray ?? undefined}
    />
  {/each}

  <!-- Children in z-order. -->
  {#each layout.children as child (child.instance.id)}
    <ChildDiagramView
      {child}
      {interactive}
      {explore}
      focused={explore && child.instance.id === focusedId}
      {tokens}
      colorClass={childColorClass(child)}
      {formatResolver}
      {style}
      {showPositionLabels}
      {showBusBarLabels}
      {showConnectionLabels}
      {showChildNames}
      {notFoundLabel}
      on:childdown
      on:childfocus
      on:elementactivate
      on:labeldown
    />
  {/each}

  <!-- Selection + rotation chrome on top. -->
  {#if selectedChild}
    <SelectionFrame child={selectedChild} {interactive} on:rotatestart />
  {/if}

  <!-- Manual-line chrome on top: hit targets for selection + bend handles. -->
  {#if !drawMode}
    {#each layout.lines as ln (ln.line.id)}
      <polyline
        points={ln.points.map((p) => `${p.x},${p.y}`).join(' ')}
        fill="none"
        stroke="transparent"
        stroke-width={style.hitStrokeWidth}
        class:pointer-events-auto={interactive}
        class:cursor-pointer={interactive}
        on:pointerdown={(e) => handleLineDown(ln.line.id, e)}
      />
    {/each}
  {/if}

  <!-- All bend chrome needs vertex ↔ point 1:1 so a vertex index maps straight to
       its resolved world position (a `rel` bend has no absolute coords of its own,
       so handles are drawn at the resolved point). If some vertex didn't resolve,
       the mapping breaks and we hide the handles rather than misplace them. -->
  {#if selectedLine && interactive && !drawMode && selectedLine.points.length === selectedLine.line.vertices.length}
    <!-- Hollow "add" handles at each segment midpoint: click-drag to insert a
         new bend; the segment index maps straight to a vertex insert position. -->
    {#each selectedLine.points.slice(0, -1) as p, i}
      <!-- svelte-ignore a11y-no-static-element-interactions -->
      <circle
        cx={(p.x + selectedLine.points[i + 1].x) / 2}
        cy={(p.y + selectedLine.points[i + 1].y) / 2}
        r={cs.addHandleRadius}
        class="fill-background stroke-primary/50 pointer-events-auto cursor-copy"
        stroke-width={cs.handleStrokeWidth}
        stroke-dasharray={cs.addHandleDashArray}
        on:pointerdown={(e) =>
          handleSegmentDown(
            selectedLine.line.id,
            i,
            { x: (p.x + selectedLine.points[i + 1].x) / 2, y: (p.y + selectedLine.points[i + 1].y) / 2 },
            e
          )}
      >
        <title>Click to add a bend</title>
      </circle>
    {/each}

    <!-- Only free bend vertices are draggable; anchored ends follow their child.
         Drawn at the resolved point, not the vertex's own coords. Double-click removes. -->
    {#each selectedLine.line.vertices as v, i}
      {#if v.kind === 'point' || v.kind === 'rel'}
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <circle
          cx={selectedLine.points[i].x}
          cy={selectedLine.points[i].y}
          r={cs.vertexHandleRadius}
          class="fill-background stroke-primary pointer-events-auto cursor-grab"
          stroke-width={cs.handleStrokeWidth}
          on:pointerdown={(e) => handleVertexDown(selectedLine.line.id, i, e)}
          on:dblclick={(e) => handleVertexDblClick(selectedLine.line.id, i, e)}
        >
          <title>Drag to move · double-click to delete</title>
        </circle>
      {/if}
    {/each}
  {/if}

  <!-- Draw-mode overlay: snap targets + in-progress polyline. -->
  {#if drawMode && interactive}
    {#each snapTargets as t}
      <circle
        cx={t.point.x}
        cy={t.point.y}
        r={cs.snapHandleRadius}
        class="fill-background stroke-primary/60"
        stroke-width={cs.handleStrokeWidth}
      />
    {/each}
    {#if draftPoints.length > 0}
      {#if draftPoints.length > 1}
        <polyline
          points={draftPoints.map((p) => `${p.x},${p.y}`).join(' ')}
          fill="none"
          class="stroke-primary"
          stroke-width={cs.draftStrokeWidth}
          stroke-dasharray={cs.draftDashArray}
        />
      {/if}
      {#each draftPoints as p}
        <circle cx={p.x} cy={p.y} r={cs.draftPointRadius} class="fill-primary" />
      {/each}
    {/if}
  {/if}

  <slot />
</svg>
